### ISSUE TITLE
SMTP Mails are not working 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#239]
Release Version 1.0.1
Environment: Devlopement/ Production

**Issue:**
Outgoing mails are not received by users, Please check for the same.

**Comment by vaishaliwebkul** [comment]
EmailService.php on line 529:
Swift_TransportException {#2761 ▼
  #message: "Connection could not be established with host smtp.gmail.com [ #0]"
  #code: 0
  #file: "/home/users/vaishali.agarwal/www/html/uvdesk_ecomm/Mail-uvdesk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php"
  #line: 272
  trace: {▶}
}

**Comment by princewebkul** [comment]
this is happen because of  http host insecure connection 
you will be modify establishSocketConnection()  in  stramBuffer.php  by add the following code 

$options['ssl']['verify_peer'] = FALSE;
$options['ssl']['verify_peer_name'] = FALSE;

**Comment by piyushwebkul** [comment]
Likewise you could also change stream context options in the swiftmailer.yaml  
```
stream_options:
                ssl:
                    verify_pear: false
                    verify_pear_name: false
```
