### ISSUE TITLE
"Better" generated config integration strategy

### ISSUE THREAD

**Issue by quazardous** [uvdesk/core-framework#309]
**Description**  
Allow more flexibility with the generated configs strategy

- config/packages/swiftmailer.yaml
- config/packages/uvdesk_mailbox.yaml
- config/packages/uvdesk.yaml
- config/packages/uvdesk_extensions.yaml
(other ?)

Add a comment like `#Generated config, edit with care` in all generated config files.

Create a new `config/packages/uvdesk_configs.yaml` config (which is **never** generated) with parameters allowing to change the path of all generated config files and maybe choose the parser/writer service and if config file is updatable from admin pages.

```yaml
parameters:
    uvdesk_configs.swiftmailer.path: config/packages/uvdesk_swiftmailer.yaml
    uvdesk_configs.swiftmailer.handler: 'something'
    uvdesk_configs.swiftmailer.protected: true # means do not allow to write from admin
    uvdesk_configs.mailbox.path: config/packages/uvdesk_mailbox.yaml
    uvdesk_configs.mailbox.handler: 'something'
    uvdesk_configs.mailbox.protected: false
    uvdesk_configs.core.path: config/packages/uvdesk_core.yaml
    uvdesk_configs.core.handler: 'something'
    uvdesk_configs.core.protected: false
    uvdesk_configs.extensions.path: config/packages/uvdesk_extensions.yaml
    uvdesk_configs.extensions.handler: 'something'
    uvdesk_configs.extensions.protected: true
```

**Example**  

Create distinct sets of configs for dev or prod env.
Protect specific configs.
